"""Article type definitions."""

DEFAULT_ARTICLE_TYPES = [
    ("generic", "Generic"),
    ("building", "Building"),
    ("character", "Character"),
    ("country", "Country"),
    ("military", "Military"),
    ("god_deity", "God/Deity"),
    ("geography", "Geography"),
    ("item", "Item"),
    ("organization", "Organization"),
    ("religion", "Religion"),
    ("species", "Species"),
    ("vehicle", "Vehicle"),
    ("settlement", "Settlement"),
    ("condition", "Condition"),
    ("conflict", "Conflict"),
    ("document", "Document"),
    ("culture_ethnitity", "Culture/Ethnitity"),
    ("language", "Language"),
    ("material", "Material"),
    ("military_formation", "Military Formation"),
    ("myth", "Myth"),
    ("natural_law", "Natural Law"),
    ("plot", "Plot"),
    ("profession", "Profession"),
    ("title", "Title"),
    ("spell", "Spell"),
    ("technology", "Technology"),
    ("tradition", "Tradition"),
    ("npc", "NPC"),
    ("faction", "Faction"),
]
